import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mlopsSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Python Basics',
      items: [
        'python-basics/chapter-01-python-syntax-and-semantics',
        'python-basics/chapter-02-variables',
        'python-basics/chapter-03-data-types',
        'python-basics/chapter-04-operators',
        'python-basics/chapter-05-conditional-statements',
        'python-basics/chapter-06-loops',
        'python-basics/chapter-07-practical-applications-of-lists',
        'python-basics/chapter-08-sets',
        'python-basics/chapter-09-tuples',
        'python-basics/chapter-10-dictionaries',
        'python-basics/chapter-11-functions',
        'python-basics/chapter-12-practical-function-examples',
        'python-basics/chapter-13-lambda-functions-map-filter',
        'python-basics/chapter-14-map-function',
        'python-basics/chapter-15-filter-function',
        'python-basics/chapter-16-modules-and-packages',
        'python-basics/chapter-17-python-standard-libraries',
        'python-basics/chapter-18-file-operations',
        'python-basics/chapter-19-file-paths-os-module',
        'python-basics/chapter-20-exception-handling',
        'python-basics/chapter-21-oop-beginner-friendly',
        'python-basics/chapter-22-inheritance-beginner-friendly',
        'python-basics/chapter-23-polymorphism-beginner-friendly',
        'python-basics/chapter-24-encapsulation-beginner-friendly',
        'python-basics/chapter-25-abstraction-beginner-friendly',
        'python-basics/chapter-26-magic-methods-beginner-friendly',
        'python-basics/chapter-27-custom-exceptions-beginner-friendly',
        'python-basics/chapter-28-operator-overloading-beginner-friendly',
        'python-basics/chapter-29-iterators-beginner-friendly',
        'python-basics/chapter-30-generators-beginner-friendly',
        'python-basics/chapter-31-decorators-beginner-friendly',
        'python-basics/chapter-32-numpy-intermediate',
        'python-basics/chapters-33-34-pandas-advanced',
        'python-basics/chapter-35-pandas-reading-data-advanced',
        'python-basics/chapter-36-logging-beginner-friendly',
        'python-basics/sample-students-pandas',
      ],
    },
    {
      type: 'category',
      label: 'Python Advanced',
      items: [
        'python-advanced/chapter-01-advanced-python-patterns',
        'python-advanced/chapter-02-concurrency-sync-async',
        'python-advanced/chapter-03-real-world-http-apis',
        'python-advanced/chapter-04-pydantic-data-validation',
        'python-advanced/chapter-05-fastapi-rest-apis',
        'python-advanced/chapter-06-sqlalchemy-async-databases',
        'python-advanced/chapter-07-testing-mocking-packaging-project-structure',
        'python-advanced/capstone-01-deployment-control-center',
        'python-advanced/capstone-02-incident-response-bot',
      ],
    },
    {
      type: 'category',
      label: 'Deployment Control Center',
      items: [
        'deployment-control-center/readme',
        'deployment-control-center/requirements',
        'deployment-control-center/pyproject',
        {
          type: 'category',
          label: 'Application',
          items: [
            'deployment-control-center/app/init',
            'deployment-control-center/app/config',
            'deployment-control-center/app/db',
            'deployment-control-center/app/main',
            'deployment-control-center/app/models',
            'deployment-control-center/app/schemas',
            'deployment-control-center/app/services',
          ],
        },
        {
          type: 'category',
          label: 'Tests',
          items: ['deployment-control-center/tests/test-app'],
        },
      ],
    },
    {
      type: 'category',
      label: 'MLflow',
      items: [
        'mlflow/study-guide',
        'mlflow/getstarted',
        'mlflow/iris-classification',
        'mlflow/requirements',
      ],
    },
  ],
};

export default sidebars;
