import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'learning-path',
      label: 'Start Here: Canonical Roadmap',
    },
    {
      type: 'category',
      label: '1. Foundations Core',
      collapsed: false,
      items: [
        'foundations/linux-and-network-administration',
        'foundations/networking-fundamentals',
        'foundations/linux-kubernetes-foundations',
        'foundations/linux-debug-playbook',
      ],
    },
    {
      type: 'category',
      label: '2. Kubernetes & Containers',
      collapsed: false,
      items: [
        'foundations/kubernetes-networking-deep-dive',
        'foundations/cloud-networking-and-kubernetes-networking',
        'foundations/docker-and-container-runtime',
        'foundations/yaml-and-kubernetes-manifest-design',
        'foundations/kubernetes-gpu-ai-platforms-and-operators',
      ],
    },
    {
      type: 'category',
      label: '3. Reliability & Observability',
      collapsed: false,
      items: [
        'foundations/observability-slos-and-incident-response',
        'foundations/prometheus-grafana-and-alertmanager',
        'foundations/devops-troubleshooting-and-security-errors',
      ],
    },
    {
      type: 'category',
      label: '4. Cloud, Design & Delivery',
      collapsed: false,
      items: [
        'foundations/system-design-cloud-architecture',
        'foundations/aws-cloud-services-and-platform-design',
        'foundations/terraform-infrastructure-as-code',
        'foundations/cicd-trusted-delivery-and-platform-security',
        'foundations/delivery-systems-jenkins-github-actions-and-argocd',
        'foundations/git-and-version-control-for-platform-engineers',
      ],
    },
    {
      type: 'category',
      label: '5. Automation & Platform Services',
      collapsed: true,
      items: [
        'foundations/bash-and-shell-scripting',
        'foundations/python-for-sre',
        'foundations/ansible-and-host-automation',
        'foundations/kafka-and-event-streaming',
        'foundations/sql-and-relational-data-for-sre',
        'foundations/http-apis-and-reverse-proxy-paths',
        'foundations/azure-devops-crossover',
        'foundations/sonarqube-and-code-quality-gates',
      ],
    },
    {
      type: 'category',
      label: '6. Synthesis & Capstone',
      collapsed: true,
      items: [
        'foundations/end-to-end-project-and-capstone-patterns',
        'foundations/senior-staff-operating-manual',
      ],
    },
    {
      type: 'category',
      label: 'Practice Labs',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'hands-on-labs'},
      ],
    },
    {
      type: 'category',
      label: 'Mock Interviews',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'mock-interviews'},
      ],
    },
    {
      type: 'category',
      label: 'Supplemental: Nebius Sprint',
      collapsed: true,
      items: [
        'nebius/README',
        'nebius/company-stack-interview-guide',
        'nebius/linux-deep-dive',
        'nebius/kubernetes-cilium-production',
        'nebius/gpu-ai-infrastructure',
        'nebius/system-design',
        'nebius/coding-algorithms',
        'nebius/stress-interview-incident-response',
      ],
    },
  ],
};

export default sidebars;
