import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🎯 Nebius Sprint (10 Days)',
      collapsed: false,
      items: [
        'nebius/README',
        'nebius/company-stack-interview-guide',
        'nebius/linux-deep-dive',
        'nebius/kubernetes-cilium-production',
        'nebius/gpu-ai-infrastructure',
        'nebius/system-design',
        'nebius/coding-algorithms',
        'nebius/stress-interview-incident-response',
      ],
    },
    {
      type: 'category',
      label: 'Linux & Systems',
      collapsed: false,
      items: [
        'foundations/linux-and-network-administration',
        'foundations/linux-debug-playbook',
        'foundations/linux-kubernetes-foundations',
        'foundations/bash-and-shell-scripting',
        'foundations/python-for-sre',
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      collapsed: false,
      items: [
        'foundations/networking-fundamentals',
        'foundations/cloud-networking-and-kubernetes-networking',
        'foundations/kubernetes-networking-deep-dive',
        'foundations/http-apis-and-reverse-proxy-paths',
      ],
    },
    {
      type: 'category',
      label: 'Kubernetes & Containers',
      collapsed: false,
      items: [
        'foundations/kubernetes-gpu-ai-platforms-and-operators',
        'foundations/docker-and-container-runtime',
        'foundations/yaml-and-kubernetes-manifest-design',
      ],
    },
    {
      type: 'category',
      label: 'Observability & Reliability',
      collapsed: false,
      items: [
        'foundations/observability-slos-and-incident-response',
        'foundations/prometheus-grafana-and-alertmanager',
        'foundations/devops-troubleshooting-and-security-errors',
      ],
    },
    {
      type: 'category',
      label: 'Cloud & Infrastructure',
      collapsed: true,
      items: [
        'foundations/system-design-cloud-architecture',
        'foundations/aws-cloud-services-and-platform-design',
        'foundations/terraform-infrastructure-as-code',
        'foundations/azure-devops-crossover',
      ],
    },
    {
      type: 'category',
      label: 'CI/CD & Delivery',
      collapsed: true,
      items: [
        'foundations/cicd-trusted-delivery-and-platform-security',
        'foundations/delivery-systems-jenkins-github-actions-and-argocd',
        'foundations/git-and-version-control-for-platform-engineers',
        'foundations/sonarqube-and-code-quality-gates',
      ],
    },
    {
      type: 'category',
      label: 'Platforms & Services',
      collapsed: true,
      items: [
        'foundations/kafka-and-event-streaming',
        'foundations/ansible-and-host-automation',
        'foundations/sql-and-relational-data-for-sre',
        'foundations/senior-staff-operating-manual',
        'foundations/end-to-end-project-and-capstone-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Hands-On Labs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'hands-on-labs'}],
    },
    {
      type: 'category',
      label: 'Practice Scenarios',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'mock-interviews'}],
    },
  ],
};

export default sidebars;
