import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'doc', id: 'learning-path', label: 'Start Here: Canonical Roadmap' },
    { type: 'doc', id: 'memory-palace', label: 'Study Memory Palace' },
    { type: 'doc', id: 'module-template', label: 'How To Use Each Module' },
    {
      type: 'category',
      label: '1. Foundations Core',
      collapsed: false,
      collapsible: true,
      items: [
        { type: 'doc', id: 'foundations/linux-and-network-administration', label: 'Linux Zero To Hero' },
        { type: 'doc', id: 'foundations/networking-fundamentals', label: 'Networking Zero To Hero' },
        { type: 'doc', id: 'foundations/linux-kubernetes-foundations', label: 'Kubernetes Foundations' },
        { type: 'doc', id: 'foundations/linux-debug-playbook', label: 'Linux Debug Playbook' },
        { type: 'doc', id: 'foundations/bash-and-shell-scripting', label: 'Bash And Shell Scripting' },
        { type: 'doc', id: 'foundations/python-for-sre', label: 'Python For SRE' },
        { type: 'doc', id: 'foundations/git-and-version-control-for-platform-engineers', label: 'Git For Platform Engineers' },
      ],
    },
    {
      type: 'category',
      label: '2. Kubernetes & Containers',
      collapsed: false,
      collapsible: true,
      items: [
        { type: 'doc', id: 'foundations/docker-and-container-runtime', label: 'Docker And Container Runtime' },
        { type: 'doc', id: 'foundations/kubernetes-networking-deep-dive', label: 'Kubernetes Networking Deep Dive' },
        { type: 'doc', id: 'foundations/cloud-networking-and-kubernetes-networking', label: 'Cloud + Kubernetes Networking' },
        { type: 'doc', id: 'foundations/yaml-and-kubernetes-manifest-design', label: 'YAML And Manifest Design' },
        { type: 'doc', id: 'foundations/kubernetes-gpu-ai-platforms-and-operators', label: 'Kubernetes GPU / AI Platforms' },
      ],
    },
    {
      type: 'category',
      label: '3. Reliability & Observability',
      collapsed: false,
      collapsible: true,
      items: [
        { type: 'doc', id: 'foundations/observability-slos-and-incident-response', label: 'Observability, SLOs, Incidents' },
        { type: 'doc', id: 'foundations/prometheus-grafana-and-alertmanager', label: 'Prometheus, Grafana, Alertmanager' },
        { type: 'doc', id: 'foundations/devops-troubleshooting-and-security-errors', label: 'Troubleshooting And Security Errors' },
      ],
    },
    {
      type: 'category',
      label: '4. Cloud, Design & Delivery',
      collapsed: false,
      collapsible: true,
      items: [
        { type: 'doc', id: 'foundations/system-design-cloud-architecture', label: 'System Design And Cloud Architecture' },
        { type: 'doc', id: 'foundations/aws-cloud-services-and-platform-design', label: 'AWS Cloud Services' },
        {
          type: 'category',
          label: 'AWS Topic Study Guide',
          collapsed: false,
          collapsible: true,
          items: [{ type: 'autogenerated', dirName: 'foundations/aws' }],
        },
        { type: 'doc', id: 'foundations/terraform-infrastructure-as-code', label: 'Terraform And IaC' },
        { type: 'doc', id: 'foundations/cicd-trusted-delivery-and-platform-security', label: 'CI/CD And Trusted Delivery' },
        { type: 'doc', id: 'foundations/delivery-systems-jenkins-github-actions-and-argocd', label: 'Jenkins, GitHub Actions, ArgoCD' },
      ],
    },
    {
      type: 'category',
      label: '5. Practice Labs',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'hands-on-labs' }],
    },
    {
      type: 'category',
      label: '6. Mock Interviews',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'mock-interviews' }],
    },
    {
      type: 'category',
      label: '7. Supplemental: Nebius Sprint',
      collapsed: true,
      items: ['nebius/README'],
    },
  ],
};

export default sidebars;
