apiVersion: v1
kind: Pod
metadata:
  name: pressure-demo
spec:
  containers:
    - name: stress
      image: polinux/stress
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "700M"]
      resources:
        requests:
          cpu: "3000m"
          memory: "2Gi"
        limits:
          cpu: "3000m"
          memory: "2Gi"
